# Generated by Django 3.2 on 2023-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_profile', verbose_name='imagem'),
        ),
    ]
